[package]
name = "cosmos-airdrop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
ocular = "1.0.0-alpha-2.0.2"
serde = { version = "1.0.144", features = ["derive"] }
toml = "0.5.9"
